# This is a goreleaser.yml file for a Go project that checks JSON files for errors
# Documentation at https://goreleaser.com

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    binary: jsoncheck
    ldflags:
      - -s -w
      - -X github.com/gj1118/m/v2/constants.Version={{.Tag}}
      - -X github.com/gj1118/m/v2/constants.Commit={{.Commit}}
      - -X github.com/gj1118/m/v2/constants.Date={{.Date}}
      
archives:
  - format: tar.gz
    # Use a good naming convention
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    # Windows archives use zip
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
